
// This file has been generated by the GUI designer. Do not modify.
namespace ICSharpCode.TypeScriptBinding
{
	public partial class RenameDialog
	{
		private global::Gtk.VBox newNameVBox;
		
		private global::Gtk.Label enterNewNameLabel;
		
		private global::Gtk.Entry newNameEntry;
		
		private global::Gtk.Button cancelButton;
		
		private global::Gtk.Button okButton;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ICSharpCode.TypeScriptBinding.RenameDialog
			this.Name = "ICSharpCode.TypeScriptBinding.RenameDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("Rename");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			this.DestroyWithParent = true;
			// Internal child ICSharpCode.TypeScriptBinding.RenameDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialogVBox";
			w1.Spacing = 6;
			w1.BorderWidth = ((uint)(2));
			// Container child dialogVBox.Gtk.Box+BoxChild
			this.newNameVBox = new global::Gtk.VBox ();
			this.newNameVBox.Name = "newNameVBox";
			this.newNameVBox.Spacing = 6;
			this.newNameVBox.BorderWidth = ((uint)(10));
			// Container child newNameVBox.Gtk.Box+BoxChild
			this.enterNewNameLabel = new global::Gtk.Label ();
			this.enterNewNameLabel.Name = "enterNewNameLabel";
			this.enterNewNameLabel.Xalign = 0F;
			this.enterNewNameLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Enter new na_me:");
			this.enterNewNameLabel.UseUnderline = true;
			this.newNameVBox.Add (this.enterNewNameLabel);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.newNameVBox [this.enterNewNameLabel]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child newNameVBox.Gtk.Box+BoxChild
			this.newNameEntry = new global::Gtk.Entry ();
			this.newNameEntry.CanFocus = true;
			this.newNameEntry.Name = "newNameEntry";
			this.newNameEntry.IsEditable = true;
			this.newNameEntry.ActivatesDefault = true;
			this.newNameEntry.InvisibleChar = '●';
			this.newNameVBox.Add (this.newNameEntry);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.newNameVBox [this.newNameEntry]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			w1.Add (this.newNameVBox);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(w1 [this.newNameVBox]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Internal child ICSharpCode.TypeScriptBinding.RenameDialog.ActionArea
			global::Gtk.HButtonBox w5 = this.ActionArea;
			w5.Name = "dialogActionArea";
			w5.Spacing = 10;
			w5.BorderWidth = ((uint)(5));
			w5.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialogActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.cancelButton = new global::Gtk.Button ();
			this.cancelButton.CanDefault = true;
			this.cancelButton.CanFocus = true;
			this.cancelButton.Name = "cancelButton";
			this.cancelButton.UseStock = true;
			this.cancelButton.UseUnderline = true;
			this.cancelButton.Label = "gtk-cancel";
			this.AddActionWidget (this.cancelButton, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w6 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w5 [this.cancelButton]));
			w6.Expand = false;
			w6.Fill = false;
			// Container child dialogActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.okButton = new global::Gtk.Button ();
			this.okButton.Sensitive = false;
			this.okButton.CanDefault = true;
			this.okButton.CanFocus = true;
			this.okButton.Name = "okButton";
			this.okButton.UseStock = true;
			this.okButton.UseUnderline = true;
			this.okButton.Label = "gtk-ok";
			this.AddActionWidget (this.okButton, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w5 [this.okButton]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 421;
			this.DefaultHeight = 141;
			this.enterNewNameLabel.MnemonicWidget = this.newNameEntry;
			this.Show ();
		}
	}
}
